Documentation Standard Updates
fivetran/dbt_zendesk pull request #166
Opened 2024-08-28 19:34 UTC by fivetran-joemarkiewicz

This pull request was created automatically 🎉:

- [ ] Ensure `.github/` files have been properly updated (templates are updated and auto releaser is included)
- [ ] Confirm all appropriate end models are included in the `.quickstart/quickstart.yml` file as `public_models` (only for transform repos)
- Verify the README has made all necessary updates:
    - [ ] Removal of emojis
    - [ ] Replacing exclamation points with periods in sentences
    - [ ] Adjusting all headers to ensure only one H1 heading
    - [ ] Confirming a section header is included for Quickstart UI rendering (only for transform repos)
    - [ ] Renaming `**model` to `**table**` (only for transform repos)
    - [ ] Removal of Fivetran community and office hour resources (if necessary)

2024-08-28 21:55 UTC, fivetran-joemarkiewicz commented on README.md
> +- Calculates SLA policy breaches for Zendesk Support Professional or Enterprise users
```suggestion
  - Creates an enriched ticket model with relevant resolution, response time, and other metrics
  - Produces a historical ticket field history model to see velocity of your tickets over time
  - Converts metrics to business hours for Zendesk Support Professional or Enterprise users
  - Calculates SLA policy breaches for Zendesk Support Professional or Enterprise users
```

2024-08-28 21:55 UTC, fivetran-joemarkiewicz commented on README.md
>  | **model**                    | **description**                                                                                                                                                 |
```suggestion
The following table provides a detailed list of final tables materialized within this package by default.
> TIP: See more details about these tables in the package's [dbt docs site](https://fivetran.github.io/dbt_zendesk/#!/overview?g_v=1).

| **Table**                    | **Description**                                                                                                                                                 |
```

2024-08-29 18:29 UTC, fivetran-joemarkiewicz commented
@fivetran-catfritz when you have a chance would you be able to review this PR? This way we can batch it along with the other changes planned for the `v0.17.0` release.

2024-08-29 19:44 UTC, fivetran-catfritz requested changes
One of the exclamation marks made it through, but otherwise is in order! @fivetran-joemarkiewicz

2024-08-29 19:44 UTC, fivetran-catfritz commented on README.md
>  Many of the above reports are now configurable for [visualization via Streamlit](https://github.com/fivetran/streamlit_zendesk)! Check out some [sample reports here](https://fivetran-zendesk.streamli
```suggestion
Many of the above reports are now configurable for [visualization via Streamlit](https://github.com/fivetran/streamlit_zendesk). Check out some [sample reports here](https://fivetran-zendesk.streamlit.app/).
```

2024-08-29 19:57 UTC, fivetran-joemarkiewicz commented
@fivetran-catfritz thanks for catching that. Let me know if this is good for approval following that change.

2024-08-29 20:39 UTC, fivetran-catfritz approved these changes
lgtm!

2024-08-30 17:22 UTC, merged